### ISSUE TITLE
Handle partial results with HTTP 206 status code

### ISSUE THREAD

**Issue by ehrhart** [D2KLab/sparql-transformer#33]
Virtuoso has a feature called "Anytime query" which can return [partial results with an HTTP 206 status code](https://community.openlinksw.com/t/technology-update-virtuoso-anytime-query-functionality-for-query-scalability/3388#http-status-code-206-partial-8).
 
Currently, sparql-transformer just throws an error when it gets partial results.

One solution is to edit SparqlClient to **NOT** throw on HTTP 206 but instead return the results just like HTTP 200.

**Comment by pasqLisena** [comment]
I am modifying it by allowing all 2xx responses to return data (as they are 200)
