### ISSUE TITLE
How to do filters based on label?

### ISSUE THREAD

**Issue by dgarijo** [D2KLab/sparql-transformer#5]
Since the labels are bound to the name property in the examples, I don't see how can I know the name of the variable associated to the label in a query. For example, the query below worked, but I had to know v2 is bound to rdfs:label :
```
{
  "@context": "http://schema.org/",
  "@graph": [{
    "@type": "City",
    "@id" : "?id",
    "name": "$rdfs:label$required",
    "image": "$foaf:depiction$required"
  }],
  "$where": [
    "?id a dbo:City",
    "?id dbo:country dbr:Italy"
  ],
  "$filter": [
    "contains(?v2,'M') "
  ],
  "$limit": 100
}
```

**Comment by pasqLisena** [comment]
Hello @dgarijo,
the variable names are assigned automatically UNLESS you specify them using the `$var:chosenName` modifier (as documented [here](https://github.com/D2KLab/sparql-transformer#the-prototype)).

For example, your query can be written as:

```json
{
  "@context": "http://schema.org/",
  "@graph": [{
    "@type": "City",
    "@id" : "?id",
    "name": "$rdfs:label$required$var:label",
    "image": "$foaf:depiction$required"
  }],
  "$where": [
    "?id a dbo:City",
    "?id dbo:country dbr:Italy"
  ],
  "$filter": [
    "contains(?label,'M') "
  ],
  "$limit": 100
}
```

**Comment by dgarijo** [comment]
I see, thanks!
